# Generated by Django 4.1.7 on 2023-05-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('MS', 'Milkshake'), ('IC', 'Ice-cream'), ('GH', 'Ghee'), ('LS', 'Lassi'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('PN', 'Paneer'), ('ML', 'Milk')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
