# Generated by Django 4.1.7 on 2023-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('LS', 'Lassi'), ('IC', 'Ice-cream'), ('ML', 'Milk'), ('MS', 'Milkshake'), ('CZ', 'Cheese'), ('GH', 'Ghee'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
