# Generated by Django 4.1.7 on 2023-05-16 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_product_composition_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('ML', 'Milk'), ('IC', 'Ice-cream'), ('MS', 'Milkshake')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Odisha', 'Odisha'), ('Delhi', 'Delhi'), ('Kerala', 'Kerala'), ('Mizoram', 'Mizoram'), ('Chhattisgarh', 'Chhattisgarh'), ('Jharkhand', 'Jharkhand'), ('Tamil Nadu', 'Tamil Nadu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Sikkim', 'Sikkim'), ('Haryana', 'Haryana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Karnataka', 'Karnataka'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Meghalaya', 'Meghalaya'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Nagaland', 'Nagaland'), ('Gujarat', 'Gujarat'), ('Goa', 'Goa'), ('West Bengal', 'West Bengal'), ('Maharashtra', 'Maharashtra'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Manipur', 'Manipur')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
